import { jsPDF } from 'jspdf';

/**
 * Generates and downloads a clean, beautifully formatted SMRITI AI Game Result Sheet PDF.
 *
 * @param {Object} params
 * @param {Object} params.report - The game result metrics { date, timestamp, totalRounds, correctCount, accuracy, score }
 * @param {string} params.aiReflection - The AI reflection text generated by Gemini
 * @param {string} [params.patientName] - Optional patient display name
 * @param {boolean} [params.autoDownload=true] - Whether to trigger browser download
 * @returns {jsPDF} The jsPDF document instance
 */
export function generateGameResultPdf({
  report = {},
  aiReflection = '',
  patientName = 'Patient',
  autoDownload = true,
}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth(); // 210mm
  const pageHeight = doc.internal.pageSize.getHeight(); // 297mm
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;

  // SMRITI Palette Colors
  const deepTeal = [0, 94, 83];
  const softMint = [212, 242, 232];
  const lightBg = [249, 249, 248];
  const textDark = [27, 28, 27];
  const textMuted = [100, 116, 139];
  const borderGray = [226, 232, 240];

  // 1. Subtle SMRITI Background Watermark
  doc.setTextColor(240, 247, 244);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(54);
  doc.text('SMRITI', pageWidth / 2, pageHeight / 2 - 10, {
    align: 'center',
    angle: 35,
  });

  // 2. Top Header Banner (Deep Teal)
  doc.setFillColor(...deepTeal);
  doc.roundedRect(margin, 16, contentWidth, 28, 4, 4, 'F');

  // Header Title
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('SMRITI', margin + 8, 26);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...softMint);
  doc.text('AI Game Result Sheet — Memory Challenge', margin + 8, 36);

  // Date Tag (Top Right)
  const sessionDate = report.date || new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const sessionTime = report.timestamp || new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text(`${sessionDate} ${sessionTime}`, pageWidth - margin - 8, 26, { align: 'right' });

  let curY = 52;

  // 3. Performance Summary Card (Light Surface with Border)
  doc.setFillColor(...lightBg);
  doc.setDrawColor(...borderGray);
  doc.setLineWidth(0.5);
  doc.roundedRect(margin, curY, contentWidth, 42, 3, 3, 'FD');

  doc.setTextColor(...deepTeal);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('GAME PERFORMANCE SUMMARY', margin + 8, curY + 9);

  // Metric Columns
  const colWidth = (contentWidth - 16) / 4;
  const metrics = [
    { label: 'Rounds Completed', value: `${report.totalRounds || 5}` },
    { label: 'Correct Answers', value: `${report.correctCount ?? 0} / ${report.totalRounds || 5}` },
    { label: 'Recall Accuracy', value: `${report.accuracy ?? 0}%` },
    { label: 'Points Earned', value: `+${report.score ?? 0}` },
  ];

  metrics.forEach((m, idx) => {
    const colX = margin + 8 + idx * colWidth;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...textMuted);
    doc.text(m.label, colX, curY + 22);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...deepTeal);
    doc.text(m.value, colX, curY + 33);
  });

  curY += 50;

  // 4. SMRITI Assistant Reflection Card (Soft Mint Accent)
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(187, 247, 208);
  doc.setLineWidth(0.6);

  // Measure text height for dynamic card sizing
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  const reflectionLines = doc.splitTextToSize(
    aiReflection || 'You completed today’s memory challenge. Great job participating in your daily cognitive exercise!',
    contentWidth - 16
  );
  const reflectionCardHeight = Math.max(34, 18 + reflectionLines.length * 6.5);

  doc.roundedRect(margin, curY, contentWidth, reflectionCardHeight, 3, 3, 'FD');

  doc.setTextColor(...deepTeal);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('SMRITI ASSISTANT REFLECTION', margin + 8, curY + 9);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(20, 83, 45); // Dark green
  doc.text(reflectionLines, margin + 8, curY + 18);

  curY += reflectionCardHeight + 12;

  // 5. About This Report Section
  doc.setTextColor(...textDark);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('About This Report', margin, curY);
  curY += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...textMuted);
  const aboutText =
    'This report was generated from the Memory Game result recorded in SMRITI. ' +
    'The AI-generated reflection is based only on the game performance data available for this session.';
  const aboutLines = doc.splitTextToSize(aboutText, contentWidth);
  doc.text(aboutLines, margin, curY);
  curY += aboutLines.length * 4.5 + 8;

  // 6. Medical & Informational Safety Disclaimer Box
  doc.setFillColor(254, 242, 242);
  doc.setDrawColor(254, 202, 202);
  doc.roundedRect(margin, curY, contentWidth, 24, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(153, 27, 27); // Dark red
  doc.text('Informational Notice & Medical Disclaimer:', margin + 6, curY + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(185, 28, 28);
  const disclaimerText =
    'This report is for informational purposes only. It is not a medical diagnosis, clinical assessment, ' +
    'treatment recommendation, or prescription. Game scores reflect exercise participation only.';
  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 12);
  doc.text(disclaimerLines, margin + 6, curY + 13);

  // 7. Footer
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...textMuted);
  doc.text('SMRITI — Cognitive Health & Memory Care Companion', pageWidth / 2, pageHeight - 12, {
    align: 'center',
  });

  // 8. Generate sanitized filename & save
  const todayIso = new Date().toISOString().split('T')[0];
  const sanitizedFilename = `SMRITI_AI_Game_Result_${todayIso}.pdf`;

  if (autoDownload) {
    doc.save(sanitizedFilename);
  }

  return { doc, filename: sanitizedFilename };
}
