import { supabase, isSupabaseConfigured } from './supabase';

/**
 * Convert VAPID base64 URL safe string to Uint8Array for PushManager
 */
export function urlBase64ToUint8Array(base64String) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Register the Service Worker in public/sw.js
 */
export async function registerServiceWorker() {
  if (typeof window === 'undefined' || !('serviceWorker' in navigator)) {
    return null;
  }

  try {
    const registration = await navigator.serviceWorker.register('/sw.js', {
      scope: '/',
    });
    return registration;
  } catch (err) {
    console.error('[PushNotifications] Service Worker registration failed:', err);
    return null;
  }
}

/**
 * Check if Web Push is supported on this browser/environment
 */
export function isPushNotificationSupported() {
  if (typeof window === 'undefined') return false;
  return (
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
}

/**
 * Get the current push subscription from PushManager if it exists
 */
export async function getExistingPushSubscription() {
  if (!isPushNotificationSupported()) return null;

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();
    return subscription;
  } catch (err) {
    console.warn('[PushNotifications] Error fetching push subscription:', err);
    return null;
  }
}

/**
 * Subscribe the caregiver's current browser/device to Web Push notifications
 */
export async function subscribeCaregiverDevice(caretakerId) {
  if (!isPushNotificationSupported()) {
    return {
      success: false,
      error: new Error('Push notifications are not supported in this browser.'),
    };
  }

  if (!caretakerId) {
    return {
      success: false,
      error: new Error('Caretaker ID is required to register device.'),
    };
  }

  const vapidPublicKey = import.meta.env.VITE_VAPID_PUBLIC_KEY;
  if (!vapidPublicKey) {
    console.error('[PushNotifications] Missing VITE_VAPID_PUBLIC_KEY in environment variables.');
    return {
      success: false,
      error: new Error('VAPID Public Key is not configured in client environment.'),
    };
  }

  try {
    // 1. Request Notification Permission
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      return {
        success: false,
        error: new Error(
          permission === 'denied'
            ? 'Notification permission was denied. Please allow notifications in your browser settings.'
            : 'Notification permission was not granted.'
        ),
      };
    }

    // 2. Ensure Service Worker is ready
    let registration = await navigator.serviceWorker.getRegistration();
    if (!registration) {
      registration = await registerServiceWorker();
    }
    if (!registration) {
      throw new Error('Could not initialize service worker.');
    }
    await navigator.serviceWorker.ready;

    // 3. Obtain or create PushSubscription
    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      const convertedVapidKey = urlBase64ToUint8Array(vapidPublicKey);
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey,
      });
    }

    // 4. Extract subscription keys
    const rawSubscription = subscription.toJSON();
    const endpoint = rawSubscription.endpoint;
    const p256dh = rawSubscription.keys?.p256dh;
    const auth = rawSubscription.keys?.auth;

    if (!endpoint || !p256dh || !auth) {
      throw new Error('Invalid push subscription keys generated by browser.');
    }

    // 5. Store/Sync in Supabase caregiver_devices table
    if (isSupabaseConfigured) {
      const { data, error } = await supabase
        .from('caregiver_devices')
        .upsert(
          {
            caretaker_id: caretakerId,
            endpoint,
            p256dh,
            auth,
            user_agent: navigator.userAgent || 'Unknown Device',
            is_active: true,
            updated_at: new Date().toISOString(),
          },
          {
            onConflict: 'caretaker_id,endpoint',
          }
        )
        .select()
        .single();

      if (error) {
        console.error('[PushNotifications] Error saving to caregiver_devices:', error);
        throw error;
      }

      return {
        success: true,
        data,
        subscription,
      };
    }

    return {
      success: true,
      subscription,
    };
  } catch (err) {
    console.error('[PushNotifications] subscribeCaregiverDevice error:', err);
    return {
      success: false,
      error: err,
    };
  }
}

/**
 * Unsubscribe current browser device from Web Push notifications
 */
export async function unsubscribeCaregiverDevice(caretakerId) {
  if (!isPushNotificationSupported()) return { success: true };

  try {
    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;

      // Mark inactive in Supabase
      if (isSupabaseConfigured && caretakerId) {
        await supabase
          .from('caregiver_devices')
          .update({ is_active: false, updated_at: new Date().toISOString() })
          .match({ caretaker_id: caretakerId, endpoint });
      }

      // Unsubscribe from browser push manager
      await subscription.unsubscribe();
    }

    return { success: true };
  } catch (err) {
    console.error('[PushNotifications] Error unsubscribing:', err);
    return { success: false, error: err };
  }
}
